_wandb:
    value:
        cli_version: 0.23.1
        e:
            gqehj22z5z0md2osgvgjb4z27m8kgmmn:
                codePath: loan_classifier.py
                codePathLocal: loan_classifier.py
                cpu_count: 10
                cpu_count_logical: 12
                disk:
                    /:
                        total: "254973698048"
                        used: "156767617024"
                email: mouadkhaled2004@gmail.com
                executable: C:\Users\DELL\AppData\Local\Programs\Python\Python313\python.exe
                host: KhaledoO
                memory:
                    total: "33658920960"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\DELL\SEDS\MLOPS Project\loan_classifier.py
                python: CPython 3.13.9
                root: C:\Users\DELL\SEDS\MLOPS Project
                startedAt: "2025-12-27T16:46:13.021227Z"
                writerId: gqehj22z5z0md2osgvgjb4z27m8kgmmn
        m: []
        python_version: 3.13.9
        t:
            "1":
                - 5
                - 6
                - 53
                - 105
            "2":
                - 5
                - 6
                - 53
                - 105
            "3":
                - 2
                - 14
            "4": 3.13.9
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
colsample_bytree:
    value: 0.6812900914775893
learning_rate:
    value: 0.05567731172762737
max_depth:
    value: 7
n_estimators:
    value: 500
subsample:
    value: 0.9187550077426568
