_wandb:
    value:
        cli_version: 0.23.1
        e:
            7vxecekyd82mhacfpm8qan290l4yq53a:
                codePath: loan_classifier.py
                codePathLocal: loan_classifier.py
                cpu_count: 10
                cpu_count_logical: 12
                disk:
                    /:
                        total: "254973698048"
                        used: "156769054720"
                email: mouadkhaled2004@gmail.com
                executable: C:\Users\DELL\AppData\Local\Programs\Python\Python313\python.exe
                host: KhaledoO
                memory:
                    total: "33658920960"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\DELL\SEDS\MLOPS Project\loan_classifier.py
                python: CPython 3.13.9
                root: C:\Users\DELL\SEDS\MLOPS Project
                startedAt: "2025-12-27T16:48:36.274374Z"
                writerId: 7vxecekyd82mhacfpm8qan290l4yq53a
        m: []
        python_version: 3.13.9
        t:
            "1":
                - 5
                - 6
                - 53
                - 105
            "2":
                - 5
                - 6
                - 53
                - 105
            "3":
                - 2
                - 14
            "4": 3.13.9
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
colsample_bytree:
    value: 0.7544207651700006
learning_rate:
    value: 0.030952487598058624
max_depth:
    value: 9
n_estimators:
    value: 300
subsample:
    value: 0.950556292018865
