_wandb:
    value:
        cli_version: 0.23.1
        e:
            xbgvb62asyaczo1km8cwseheutvtc4fn:
                codePath: loan_classifier.py
                codePathLocal: loan_classifier.py
                cpu_count: 10
                cpu_count_logical: 12
                disk:
                    /:
                        total: "254973698048"
                        used: "156688605184"
                email: mouadkhaled2004@gmail.com
                executable: C:\Users\DELL\AppData\Local\Programs\Python\Python313\python.exe
                host: KhaledoO
                memory:
                    total: "33658920960"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\DELL\SEDS\MLOPS Project\loan_classifier.py
                python: CPython 3.13.9
                root: C:\Users\DELL\SEDS\MLOPS Project
                startedAt: "2025-12-27T16:35:53.310422Z"
                writerId: xbgvb62asyaczo1km8cwseheutvtc4fn
        m: []
        python_version: 3.13.9
        t:
            "1":
                - 5
                - 6
                - 53
                - 105
            "2":
                - 5
                - 6
                - 53
                - 105
            "3":
                - 2
            "4": 3.13.9
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
